> apply() Ne yapar: Bir sütuna ya da tabloya kendi yazdığın fonksiyonu uygular.

> sum(), mean(), count(), max(), min() gibi hazır fonksiyonlar her şeyi çözmez. Bazen kendi mantığını yazman gerekir. İşte o zaman apply devreye girer.

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'category': ['Elektronik', 'Giyim', 'Elektronik', 'Giyim', 'Gida'],
    'sales':    [500, 300, 700, 200, 150],
    'pcs':     [2, 5, 3, 4, 1]
})

In [4]:
df.groupby('category').apply(lambda x: x['sales'] * 1.18) # apply ile kendi fonksiyonumuzu yazabiliriz, burada satışlara KDV ekledik

category
Elektronik  0    590.0
            2    826.0
Gida        4    177.0
Giyim       1    354.0
            3    236.0
Name: sales, dtype: float64

In [11]:
df["sales_tax"] = df['sales'].apply(lambda x: x * 1.18)
df

     category  sales  pcs  sales_tax
0  Elektronik    500    2      590.0
1       Giyim    300    5      354.0
2  Elektronik    700    3      826.0
3       Giyim    200    4      236.0
4        Gida    150    1      177.0

In [12]:
df.groupby('category')['sales_tax'].sum()

category
Elektronik    1416.0
Gida           177.0
Giyim          590.0
Name: sales_tax, dtype: float64

In [15]:
df['only_tax'] = df['sales_tax'] - df['sales']
df

     category  sales  pcs  sales_tax  only_tax
0  Elektronik    500    2      590.0      90.0
1       Giyim    300    5      354.0      54.0
2  Elektronik    700    3      826.0     126.0
3       Giyim    200    4      236.0      36.0
4        Gida    150    1      177.0      27.0

In [21]:
df.groupby('category')['only_tax'].sum()
# df.sum()

category
Elektronik    216.0
Gida           27.0
Giyim          90.0
Name: only_tax, dtype: float64

In [39]:
def labling(sales):
    if sales >= 500:
        return 'High'
    elif sales >= 200:
        return 'Medium'
    else:
        return 'Low'

df['price_label'] = df['sales'].apply(labling)
df['mean_tax'] = df.groupby('category')['only_tax'].transform('sum') # transform ile her satır için o kategorinin toplam vergisini yazdırdık
df

     category  sales  pcs  sales_tax  only_tax price_label  mean_tax
0  Elektronik    500    2      590.0      90.0        High     216.0
1       Giyim    300    5      354.0      54.0      Medium      90.0
2  Elektronik    700    3      826.0     126.0        High     216.0
3       Giyim    200    4      236.0      36.0      Medium      90.0
4        Gida    150    1      177.0      27.0         Low      27.0